version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 10s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - notification-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - /app/node_modules
    environment:
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      WAIT_FOR_RABBITMQ: "true"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - notification-network

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - notification-network

volumes:
  rabbitmq_data:

networks:
  notification-network:
    driver: bridge
